trigger:
- main

variables:
  # Use the service connection ID for ACR access
  dockerRegistryServiceConnection: 'myacrcred'  # The service connection name for ACR
  imageRepository: 'app1/app1nginx'
  containerRegistry: 'aksdevopsacr.azurecr.io'  # Your ACR URL
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  manifestsPath: 'Kube-Manifests/'
  k8sServiceConnection: 'myakscred' 
  tag: '$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push Docker Image to ACR
    pool: "Default"
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    ## Publish Artifacts pipeline code in addition to Build and Push
    - bash: echo "Contents in System Default Working Directory"; ls -R $(System.DefaultWorkingDirectory)
    - bash: echo "Before copying Contents in Build Artifact Directory"; ls -R $(Build.ArtifactStagingDirectory)
    
    # Task-2: Copy files (Copy files from a source folder to target folder)
    # Source Directory: $(System.DefaultWorkingDirectory)/kube-manifests
    # Target Directory: $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/Kube-Manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true
        
    # List files from Build Artifact Staging Directory - After Copy
    - bash: echo "After copying to Build Artifact Directory"; ls -R $(Build.ArtifactStagingDirectory)
    
    # Task-3: Publish build artifacts (Publish build to Azure Pipelines)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'

- stage: DeployToAKS
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy to AKS using Kubernetes Manifests
    pool: "Default"
    steps:
    - checkout: self
    - task: KubernetesManifest@0
      displayName: Deploy Kubernetes Manifests to AKS
      inputs:
        kubernetesServiceConnection: $(k8sServiceConnection)
        namespace: default
        manifests: |
          $(System.DefaultWorkingDirectory)/$(manifestsPath)/*.yaml
        containers: |
          $(containerRegistry)/$(imageRepository):$(tag)
