apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: $(containerRegistry)/$(imageRepository):$(tag)
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: acrpull-secret
